require(tidyverse) 
path_to_CDI="/Users/elinlarsen/GoogleDrive/PhD_elin/Projets/CDSwordseg_Pipeline/CDI/english/"
path_to_CDI_lexClass="/Users/elinlarsen/GoogleDrive/PhD_elin/Projets/CDSwordSeg_Pipeline//CDI/english/CDI_lexical_classes.txt"
path_to_prop_cdi="~/Google Drive/CDSwordSeg_Pipeline/results/res-brent-CDS/Analysis_algos_CDI/CDI_data/PropUnderstandCDI.csv"

lexClass <- read_delim(path_to_CDI_lexClass, "\t", escape_double = FALSE, trim_ws = TRUE)
head(lexClass)
ggplot(lexClass, aes(x=lexical_classes))+
  geom_bar()

lexClass$lexical_classes[lexClass$Type=="yum yum"]="onomatopoeia"
lexClass$lexical_classes[lexClass$Type=="aunt"]="nouns"
lexClass$lexical_classes[lexClass$Type=="baa baa"]="onomatopoeia"
lexClass$lexical_classes[lexClass$Type=="baby"]="nouns"
lexClass$lexical_classes[lexClass$Type=="babysitter"]="nouns"
lexClass$lexical_classes[lexClass$Type=="bath"]="nouns"
lexClass$lexical_classes[lexClass$Type=="boy"]="nouns"
lexClass$lexical_classes[lexClass$Type=="breakfast"]="nouns"
lexClass$lexical_classes[lexClass$Type=="brother"]="nouns"
lexClass$lexical_classes[lexClass$Type=="bye"]="exclamation"
lexClass$lexical_classes[lexClass$Type=="child"]="nouns"
lexClass$lexical_classes[lexClass$Type=="choo choo"]="onomatopoeia"
lexClass$lexical_classes[lexClass$Type=="cockadoodledoo"]="onomatopoeia"
lexClass$lexical_classes[lexClass$Type=="daddy"]="nouns"
lexClass$lexical_classes[lexClass$Type=="day"]="nouns"
lexClass$lexical_classes[lexClass$Type=="dinner"]="nouns"
lexClass$lexical_classes[lexClass$Type=="don't"]="verbs"
lexClass$lexical_classes[lexClass$Type=="girl"]="nouns"
lexClass$lexical_classes[lexClass$Type=="grandma"]="nouns"
lexClass$lexical_classes[lexClass$Type=="grandpa"]="nouns"
lexClass$lexical_classes[lexClass$Type=="grr"]="onomatopoeia"
lexClass$lexical_classes[lexClass$Type=="hello"]="exclamation"
lexClass$lexical_classes[lexClass$Type=="hi"]="exclamation"
lexClass$lexical_classes[lexClass$Type=="lady"]="nouns"
lexClass$lexical_classes[lexClass$Type=="later"]="adverbs"
lexClass$lexical_classes[lexClass$Type=="lunch"]="nouns"
lexClass$lexical_classes[lexClass$Type=="man"]="nouns"
lexClass$lexical_classes[lexClass$Type=="meow"]="onomatopoeia"
lexClass$lexical_classes[lexClass$Type=="mommy"]="nouns"
lexClass$lexical_classes[lexClass$Type=="moo"]="onomatopoeia"
lexClass$lexical_classes[lexClass$Type=="morning"]="nouns"
lexClass$lexical_classes[lexClass$Type=="night"]="nouns"
lexClass$lexical_classes[lexClass$Type=="nap"]="nouns"
lexClass$lexical_classes[lexClass$Type=="no"]="exclamation"
lexClass$lexical_classes[lexClass$Type=="now"]="adverbs"
lexClass$lexical_classes[lexClass$Type=="ouch"]="onomatopoeia"
lexClass$lexical_classes[lexClass$Type=="peekaboo"]="onomatopoeia"
lexClass$lexical_classes[lexClass$Type=="people"]="nouns"
lexClass$lexical_classes[lexClass$Type=="please"]="exclamation"
lexClass$lexical_classes[lexClass$Type=="person"]="nouns"
lexClass$lexical_classes[lexClass$Type=="quack quack"]="onomatopoeia"
lexClass$lexical_classes[lexClass$Type=="shh"]="onomatopoeia"
lexClass$lexical_classes[lexClass$Type=="sister"]="nouns"
lexClass$lexical_classes[lexClass$Type=="teacher"]="nouns"
lexClass$lexical_classes[lexClass$Type=="thank you"]="exclamation"
lexClass$lexical_classes[lexClass$Type=="today"]="adverbs"
lexClass$lexical_classes[lexClass$Type=="tomorrow"]="adverbs"
lexClass$lexical_classes[lexClass$Type=="tonight"]="adverbs"
lexClass$lexical_classes[lexClass$Type=="uh oh"]="onomatopoeia"
lexClass$lexical_classes[lexClass$Type=="uncle"]="nouns"
lexClass$lexical_classes[lexClass$Type=="vroom"]="onomatopoeia"
lexClass$lexical_classes[lexClass$Type=="wait"]="verbs"
lexClass$lexical_classes[lexClass$Type=="shh"]="onomatopoeia"
lexClass$lexical_classes[lexClass$Type=="wanna"]="verbs"
lexClass$lexical_classes[lexClass$Type=="woof woof"]="onomatopoeia"
lexClass$lexical_classes[lexClass$Type=="yes"]="exclamation"


#Defining nex lexical categories

#Proportion of infants reported to understand a word in CDI at different ages**
#prop_cdi <- read_delim(path_to_lexClass, "\t", escape_double = FALSE, trim_ws = TRUE) %>%
  #select(Type, prop,age, lexical_classes)

#lexClass$age<-as.factor(lexClass$age)

#changind some types**
lexClass$Type<-gsub("wanna/want to", "wanna", lexClass$Type)
lexClass$Type<-gsub("shh/shush/hush", "shh", lexClass$Type)

#Renaming the lexical class "other"
other<-lexClass%>%
  filter(lexical_classes=="other")%>%
  select(Type)

#other=as.data.frame(other$Type, columns.names="Type")

lexClass$lexical_classes[lexClass$Type=="yum yum"]="onomatopoeia"
lexClass$lexical_classes[lexClass$Type=="aunt"]="nouns"
lexClass$lexical_classes[lexClass$Type=="baa baa"]="onomatopoeia"
lexClass$lexical_classes[lexClass$Type=="baby"]="nouns"
lexClass$lexical_classes[lexClass$Type=="babysitter"]="nouns"
lexClass$lexical_classes[lexClass$Type=="bath"]="nouns"
lexClass$lexical_classes[lexClass$Type=="boy"]="nouns"
lexClass$lexical_classes[lexClass$Type=="breakfast"]="nouns"
lexClass$lexical_classes[lexClass$Type=="brother"]="nouns"
lexClass$lexical_classes[lexClass$Type=="bye"]="exclamation"
lexClass$lexical_classes[lexClass$Type=="child"]="nouns"
lexClass$lexical_classes[lexClass$Type=="choo choo"]="onomatopoeia"
lexClass$lexical_classes[lexClass$Type=="cockadoodledoo"]="onomatopoeia"
lexClass$lexical_classes[lexClass$Type=="daddy"]="nouns"
lexClass$lexical_classes[lexClass$Type=="day"]="nouns"
lexClass$lexical_classes[lexClass$Type=="dinner"]="nouns"
lexClass$lexical_classes[lexClass$Type=="don't"]="verbs"
lexClass$lexical_classes[lexClass$Type=="girl"]="nouns"
lexClass$lexical_classes[lexClass$Type=="grandma"]="nouns"
lexClass$lexical_classes[lexClass$Type=="grandpa"]="nouns"
lexClass$lexical_classes[lexClass$Type=="grr"]="onomatopoeia"
lexClass$lexical_classes[lexClass$Type=="hello"]="exclamation"
lexClass$lexical_classes[lexClass$Type=="hi"]="exclamation"
lexClass$lexical_classes[lexClass$Type=="lady"]="nouns"
lexClass$lexical_classes[lexClass$Type=="later"]="adverbs"
lexClass$lexical_classes[lexClass$Type=="lunch"]="nouns"
lexClass$lexical_classes[lexClass$Type=="man"]="nouns"
lexClass$lexical_classes[lexClass$Type=="meow"]="onomatopoeia"
lexClass$lexical_classes[lexClass$Type=="mommy"]="nouns"
lexClass$lexical_classes[lexClass$Type=="moo"]="onomatopoeia"
lexClass$lexical_classes[lexClass$Type=="morning"]="nouns"
lexClass$lexical_classes[lexClass$Type=="night"]="nouns"
lexClass$lexical_classes[lexClass$Type=="nap"]="nouns"
lexClass$lexical_classes[lexClass$Type=="no"]="exclamation"
lexClass$lexical_classes[lexClass$Type=="now"]="adverbs"
lexClass$lexical_classes[lexClass$Type=="ouch"]="onomatopoeia"
lexClass$lexical_classes[lexClass$Type=="peekaboo"]="onomatopoeia"
lexClass$lexical_classes[lexClass$Type=="people"]="nouns"
lexClass$lexical_classes[lexClass$Type=="please"]="exclamation"
lexClass$lexical_classes[lexClass$Type=="person"]="nouns"
lexClass$lexical_classes[lexClass$Type=="quack quack"]="onomatopoeia"
lexClass$lexical_classes[lexClass$Type=="shh"]="onomatopoeia"
lexClass$lexical_classes[lexClass$Type=="sister"]="nouns"
lexClass$lexical_classes[lexClass$Type=="teacher"]="nouns"
lexClass$lexical_classes[lexClass$Type=="thank you"]="exclamation"
lexClass$lexical_classes[lexClass$Type=="today"]="adverbs"
lexClass$lexical_classes[lexClass$Type=="tomorrow"]="adverbs"
lexClass$lexical_classes[lexClass$Type=="tonight"]="adverbs"
lexClass$lexical_classes[lexClass$Type=="uh oh"]="onomatopoeia"
lexClass$lexical_classes[lexClass$Type=="uncle"]="nouns"
lexClass$lexical_classes[lexClass$Type=="vroom"]="onomatopoeia"
lexClass$lexical_classes[lexClass$Type=="wait"]="verbs"
lexClass$lexical_classes[lexClass$Type=="shh"]="onomatopoeia"
lexClass$lexical_classes[lexClass$Type=="wanna"]="verbs"
lexClass$lexical_classes[lexClass$Type=="woof woof"]="onomatopoeia"
lexClass$lexical_classes[lexClass$Type=="yes"]="exclamation"


lexClass$lexical_classes[lexClass$Type=="all"]="determiners"
lexClass$lexical_classes[lexClass$Type=="another"]="determiners"
lexClass$lexical_classes[lexClass$Type=="away"]="adverbs"
lexClass$lexical_classes[lexClass$Type=="back"]="adverbs"
lexClass$lexical_classes[lexClass$Type=="down"]="adverbs"
lexClass$lexical_classes[lexClass$Type=="her"]="pronouns"
lexClass$lexical_classes[lexClass$Type=="his"]="pronouns"
lexClass$lexical_classes[lexClass$Type=="how"]="wh-"
lexClass$lexical_classes[lexClass$Type=="i"]="pronouns"
lexClass$lexical_classes[lexClass$Type=="in"]="prepositions"
lexClass$lexical_classes[lexClass$Type=="inside"]="prepositions"
lexClass$lexical_classes[lexClass$Type=="it"]="pronouns"
lexClass$lexical_classes[lexClass$Type=="me"]="pronouns"
lexClass$lexical_classes[lexClass$Type=="mine"]="pronouns"
lexClass$lexical_classes[lexClass$Type=="more"]="pronouns"
lexClass$lexical_classes[lexClass$Type=="my"]="determiners"
lexClass$lexical_classes[lexClass$Type=="none"]="pronouns"
lexClass$lexical_classes[lexClass$Type=="not"]="adverbs"
lexClass$lexical_classes[lexClass$Type=="off"]="adverbs"
lexClass$lexical_classes[lexClass$Type=="on"]="prepositions"
lexClass$lexical_classes[lexClass$Type=="other"]="pronouns"
lexClass$lexical_classes[lexClass$Type=="out"]="adverbs"
lexClass$lexical_classes[lexClass$Type=="same"]="pronouns"
lexClass$lexical_classes[lexClass$Type=="some"]="determiners"
lexClass$lexical_classes[lexClass$Type=="that"]="pronouns"
lexClass$lexical_classes[lexClass$Type=="there"]="adverbs"
lexClass$lexical_classes[lexClass$Type=="this"]="pronouns"
lexClass$lexical_classes[lexClass$Type=="under"]="prepositions"
lexClass$lexical_classes[lexClass$Type=="up"]="adverbs"
lexClass$lexical_classes[lexClass$Type=="what"]="wh-"
lexClass$lexical_classes[lexClass$Type=="where"]="wh-"
lexClass$lexical_classes[lexClass$Type=="when"]="wh-"
lexClass$lexical_classes[lexClass$Type=="who"]="wh-"
lexClass$lexical_classes[lexClass$Type=="why"]="wh-"
lexClass$lexical_classes[lexClass$Type=="you"]="pronouns"
lexClass$lexical_classes[lexClass$Type=="your"]="determiners"

#Writing a new file with final lexical classes***
write.table(lexClass, paste(path_to_CDI, "/New_lexclass.csv", sep=""), na = "NA", append = FALSE, col.names = TRUE, sep="\t", row.names = FALSE)
