require(tidyverse) 
require(lme4)
require(lmerTest)
library(langcog)
library(knitr)
library(kableExtra) # for table styles
library(shiny)
library(moments)
library(BayesFactor)
library(sjPlot)
library(SnowballC)
library(olsrr)
library(rlist)
source("sample_words_by_category.R")
source("sample_cdi_reports.R")
source("linear_models.R")
source("Nb_parental_reports_per_age.R")
source("read_algorithms_results.R")
